apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-pod
        image: diegochavezcarro/pythondocker:parte1
        ports:
        - containerPort: 5000
